amrf_public_rooter_homepage:
    path:     /
    defaults: { _controller: AMRFPublicRooterBundle:Default:index }

amrf_public_rooter_amrf:
    path:     /amrf
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:amrf }

amrf_public_rooter_contact:
    path:     /contact
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:contact }

amrf_public_rooter_confidential:
    path:     /confidential
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:confidential }

amrf_public_rooter_mentions:
    path:     /mentions
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:mentions }

amrf_public_rooter_search:
    path:     /search
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:search }

amrf_public_rooter_maireProfil:
    path:     /maire/profil
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:maireProfil }

amrf_public_rooter_partListe:
    path:     /partenaire/liste
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:partListe }


amrf_public_rooter_projet:
    path:     /projet
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:projet }


amrf_public_rooter_partIndex:
    path:     /partenaires
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:partIndex }

amrf_public_rooter_maireIndex:
    path:     /maire
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:maireIndex}

amrf_public_rooter_maireProjet:
    path:     /maire/projet
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:maireProjet}

amrf_public_rooter_maireFormProjet:
    path:     /maire/FormProjet
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:mairesFormProjet}


amrf_public_rooter_partListe:
    path:     /partenaire/liste
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:partListe}

amrf_public_rooter_partProfil:
    path:     /partenaire/profil
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:partProfil}

amrf_public_rooter_partFormFiche:
    path:     /partenaire/form
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:partFormFiche}

amrf_public_rooter_favoris:
    path:     /partenaire/favoris
    defaults: { _controller: AMRFPublicRooterBundle:PublicRooter:favoris}

