# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 10

    role_hierarchy:
        ROLE_MAYOR:         ROLE_MAYOR
        ROLE_PARTNER:       ROLE_PARTNER
        ROLE_ADMIN:         ROLE_ADMIN

    access_control:
        - { path: ^/mayor, roles: ROLE_MAYOR }
        - { path: ^/partner, roles: ROLE_PARTNER }
        - { path: ^/admin, roles: ROLE_ADMIN }


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: login
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 15768000 # 6 mois
                path:     /

        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
